<?php

/**
 * Implements hook_menu().
 */
function msrc_api_menu() {
	$items['documents'] = array(
    'page callback' => '_msrc_api_list',
    'access arguments' => array('access biblio content'),
    'type' => MENU_CALLBACK,
  );
  $items['documents/%'] = array(
    'page callback' => '_msrc_api_single',
    'page arguments' => array(1),
    'access arguments' => array('access biblio content'),
    'type' => MENU_CALLBACK,
  );
	return $items;
}

/**
 * Callback function for hook_menu().
 */
function _msrc_api_list() {
  $endpoint = new MSRCListHelper();
  $endpoint->showList();
}

/**
 * Callback function for hook_menu().
 */
function _msrc_api_single($bid) {
  $endpoint = new MSRCSingleRecordHelper($bid);
  $endpoint->showRecord();
}
